---

- include: package.yml
  tags: package

- name: configure ntp file
  template:
    src: ntp.j2
    dest: /etc/ntp.conf
  notify: restart_ntp
  tags: configuration

- include: service.yml
  tags: service
