---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include: package.yml
  tags: package

- name: configure ntp file
  template:
    src: ntp.j2
    dest: /etc/ntp.conf
  notify: restart_ntp
  tags: configuration

- include: service.yml
  tags: service
