---

- name: Debian | install specific NTP version
  apt:
    pkg: 'ntp={{ ntp_pkg_version }}'
    state: installed
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian' and ntp_pkg_version

- name: Debian | install current/latest NTP version
  apt:
    pkg: ntp
    state: '{{ ntp_pkg_state }}'
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian' and not ntp_pkg_version

- name: RedHat | install specific NTP version
  yum:
    name: 'ntp={{ ntp_pkg_version }}'
    state: installed
  when: ansible_os_family == 'RedHat' and ntp_pkg_version

- name: RedHat | install current/latest NTP package
  yum:
    name: ntp
    state: '{{ ntp_pkg_state }}'
  when: ansible_os_family == 'RedHat' and not ntp_pkg_version
