---

- name: Debian | enable service
  service:
    name: ntp
    state: '{{ ntp_service_state }}'
    enabled: '{{ ntp_service_enabled }}'
  when: ansible_os_family == 'Debian'

- name: RedHat | enable service
  service:
    name: ntpd
    state: '{{ ntp_service_state }}'
    enabled: '{{ ntp_service_enabled }}'
  when: ansible_os_family == 'RedHat'
